// import { v4 as uuidv4 } from "uuid";

export const initialCustomer = {
  code_societe: "",
  raison_social: "",
  form_jury: "",
  ice: "",
  region: "",
  chef_chantier: "",
  tel_chef_chantier: "",
  gerant: "",
  tel_gerant: "",
  n_compte: "",
  tel_societe: "",
  fax: "",
  courriel: "",
  adresse_facture: "",
  zipcode: "",
  ville: "",
  pays: "",
  adresse_livraison:  "",
  zipcode_livraison: "",
  ville_livraison: "",
  pays_livraison: "",
  commercial: "",
  tel_commercial: "",
}